title: Mio's food picks
author:
  name: Mio Galang

url: http://food.miogalang.com
logo: assets/images/logo.png
github_username: miogalang
email: miguelgalang@gmail.com

description: >
  This is the Mio Galang's list of places he likes to eat at

# social links
github_username: miogalang

exclude:
  - README.md

collections:
 places:
   output: true
   permalink: /:name
 restaurants:
   output: false

defaults:
  - scope:
      path: _places
      type: places
    values:
      layout: place
  - scope:
      path: _restaurants
      type: restaurant
    values:
      rank: 999

remote_theme: "mmistakes/jekyll-theme-basically-basic"
